version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"   # expose sur le port 80 de la VM
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "5000:5000"   # backend écoute sur 5000
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
