name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker image
        run: |
          docker build -t username/react-frontend:latest ./frontend
          docker push username/react-frontend:latest

      - name: Build Backend Docker image
        run: |
          docker build -t username/backend-api:latest ./backend
          docker push username/backend-api:latest
