name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ==== BACKEND BUILD ====
      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t backend-api:test .

      - name: Save backend image as artifact
        run: |
          docker save backend-api:test -o backend-api.tar
        shell: bash

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-api
          path: backend-api.tar

      # ==== FRONTEND BUILD ====
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          tar -czf react-build.tar.gz build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: frontend/react-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-api
          path: .

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: .

      # === DEBUG STEP (juste avant SCP) ===
      - name: Debug before SCP
        run: ls -lh

      # ==== DEPLOY BACKEND ====
      - name: Copy backend image to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: backend-api.tar
          target: ~/

      - name: Load and run backend container on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i ~/backend-api.tar
            docker stop backend-api || true
            docker rm backend-api || true
            docker run -d --name backend-api -p 3000:3000 backend-api:test

      # ==== DEPLOY FRONTEND ====
      - name: Copy frontend build to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: react-build.tar.gz
          target: ~/

      - name: Extract and serve frontend on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/react-app/dist
            tar -xzf ~/react-build.tar.gz -C ~/react-app/dist
            rm ~/react-build.tar.gz
            sudo systemctl restart nginx
