deploy-vm1:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: react-build
        path: .

    - name: Copy build to VM1
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM1_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: frontend/react-build.tar.gz
        target: ~/react-build.tar.gz

    - name: Deploy on VM1
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM1_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if [ ! -f ~/react-build.tar.gz ]; then
            echo "Erreur : react-build.tar.gz non trouvé dans le home"
            exit 1
          fi

          mkdir -p ~/react-app/dist

          tar -xzf ~/react-build.tar.gz -C ~/react-app/dist

          rm ~/react-build.tar.gz

          if ! command -v nginx &> /dev/null; then
            echo "Nginx non trouvé, installation en cours..."
            if [ -f /etc/debian_version ]; then
              sudo apt-get update && sudo apt-get install -y nginx
            else
              sudo yum install -y nginx
            fi
            sudo systemctl enable nginx
          fi

          sudo systemctl restart nginx
