name: Test Artifact Transfer

on:
  workflow_dispatch:  # Lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy artifacts
        run: |
          echo "frontend build $(date)" > react-frontend.txt
          echo "backend build $(date)" > backend-api.txt
          tar -czf react-frontend.tar.gz react-frontend.txt
          tar -czf backend-api.tar.gz backend-api.txt

      - name: Debug build artifacts
        run: ls -lh

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-frontend
          path: react-frontend.tar.gz

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-api
          path: backend-api.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: react-frontend

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-api

      - name: Debug downloaded artifacts
        run: ls -lh

      - name: Copy artifacts to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          source: |
            react-frontend.tar.gz
            backend-api.tar.gz
          target: /home/${{ secrets.VM_USER }}/
