name: Build & Push React Frontend to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-3
      ECR_REPO: 426941767449.dkr.ecr.eu-west-3.amazonaws.com/frontend-react

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies & build React app
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React app
        run: npm run build
        working-directory: ./frontend

      # 4. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 5. Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t frontend-react ./frontend

      # 7. Tag Docker image for ECR
      - name: Tag Docker image
        run: docker tag frontend-react:latest $ECR_REPO:latest

      # 8. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push $ECR_REPO:latest
