name: Build, Push & Deploy (multi-VM + ALB)

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world:latest
  SSH_USER: ec2-user   # ubuntu si AMI Ubuntu

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy_parallel:
    needs: build_and_push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [ "${{ secrets.HOST_1 }}", "${{ secrets.HOST_2 }}" ]
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy on ${{ matrix.host }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ matrix.host }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull $IMAGE_NAME
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name react-app -p 80:80 --restart=always $IMAGE_NAME
