name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Archive build output
        run: tar -czf react-build.tar.gz -C build .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: react-build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: .

      - name: Copy build artifact to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: react-build.tar.gz
          target: ~/react-build.tar.gz

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Supprime ancien fichier ou dossier (au cas où)
            rm -rf ~/react-build.tar.gz

            # (Debug) Liste fichiers dans home
            ls -l ~

            # Crée dossier destination
            mkdir -p ~/react-app/dist

            # Décompresse archive dans le dossier dist
            tar -xzf ~/react-build.tar.gz -C ~/react-app/dist

            # Supprime archive après extraction
            rm ~/react-build.tar.gz

            # Installe nginx si absent
            if ! command -v nginx &> /dev/null; then
              echo "Nginx non trouvé, installation en cours..."
              if [ -f /etc/debian_version ]; then
                sudo apt-get update && sudo apt-get install -y nginx
              else
                sudo yum install -y nginx
              fi
              sudo systemctl enable nginx
            fi

            # Redémarre nginx
            sudo systemctl restart nginx
