name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Archive build output
        run: tar -czf react-build.tar.gz -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: react-build.tar.gz

  deploy-vm1:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: .

      - name: Copy build to VM1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM1_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: react-build.tar.gz
          target: ~/react-build.tar.gz

      - name: Deploy on VM1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM1_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/react-app/dist
            tar -xzf ~/react-build.tar.gz -C ~/react-app/dist
            rm ~/react-build.tar.gz
            sudo systemctl restart nginx

  deploy-vm2:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: .

      - name: Copy build to VM2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM2_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: react-build.tar.gz
          target: ~/react-build.tar.gz

      - name: Deploy on VM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM2_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/react-app/dist
            tar -xzf ~/react-build.tar.gz -C ~/react-app/dist
            rm ~/react-build.tar.gz
            sudo systemctl restart nginx
