name: Build and Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  # -------------------------
  # BUILD
  # -------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Build Frontend
      - name: Build React Frontend Docker image
        run: docker build -t react-frontend:latest .
        working-directory: ./frontend

      # Build Backend
      - name: Build Backend API Docker image
        run: docker build -t backend-api:latest .
        working-directory: ./backend

      # Save and compress images
      - name: Save Docker images
        run: |
          docker save react-frontend:latest | gzip > react-frontend.tar.gz
          docker save backend-api:latest | gzip > backend-api.tar.gz

      # Upload artifacts
      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            react-frontend.tar.gz
            backend-api.tar.gz

  # -------------------------
  # DEPLOY TO VM
  # -------------------------
  deploy:
    needs: build
    runs-on: [self-hosted, app-vm]
    steps:
      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: .

      - name: Load Docker images
        run: |
          gunzip -f react-frontend.tar.gz
          docker load -i react-frontend.tar
          gunzip -f backend-api.tar.gz
          docker load -i backend-api.tar

      - name: Deploy containers with docker-compose
        run: |
          mkdir -p ~/fullstack-app
          cd ~/fullstack-app
          # Copier le docker-compose.yml depuis le repo
          cp $GITHUB_WORKSPACE/docker-compose.yml .
          docker-compose up -d
