name: Build and Deploy Fullstack App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build React Frontend Docker image
        run: docker build -t react-frontend:${{ github.sha }} .
        working-directory: ./frontend

      - name: Build Backend API Docker image
        run: docker build -t backend-api:${{ github.sha }} .
        working-directory: ./backend

      - name: Save and compress React Frontend image
        run: |
          docker save react-frontend:${{ github.sha }} -o react-frontend.tar
          gzip react-frontend.tar

      - name: Save and compress Backend API image
        run: |
          docker save backend-api:${{ github.sha }} -o backend-api.tar
          gzip backend-api.tar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            react-frontend.tar.gz
            backend-api.tar.gz

  deploy-vm1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: .

      - name: Copy Docker images to VM1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM1_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "react-frontend.tar.gz,backend-api.tar.gz"
          target: ~/

      - name: Deploy containers on VM1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM1_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Nettoyage des anciens conteneurs et images
            docker ps -aq | xargs -r docker stop
            docker ps -aq | xargs -r docker rm
            docker images -q | xargs -r docker rmi -f
            docker volume prune -f
            docker network prune -f

            # Charger les nouvelles images
            gunzip ~/react-frontend.tar.gz
            gunzip ~/backend-api.tar.gz
            docker load -i ~/react-frontend.tar
            docker load -i ~/backend-api.tar

            # Lancer les nouveaux conteneurs
            docker run -d --name react-frontend -p 80:80 react-frontend:${{ github.sha }}
            docker run -d --name backend-api -p 8000:3000 backend-api:${{ github.sha }}

            # Nettoyage des tar
            rm ~/react-frontend.tar ~/backend-api.tar
