name: Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # =====================
      # 1. Checkout du code
      # =====================
      - name: Checkout repository
        uses: actions/checkout@v3

      # =====================
      # 2. Connexion DockerHub
      # =====================
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =====================
      # 3. Build & Push Frontend
      # =====================
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest

      # =====================
      # 4. Build & Push Backend
      # =====================
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:latest

      # =====================
      # 5. Déploiement sur les VM
      # =====================
      - name: Deploy on Frontend & Backend VMs
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM1_FRONT }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/app && docker-compose pull && docker-compose up -d --build

      - name: Deploy on Frontend VM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM2_FRONT }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/app && docker-compose pull && docker-compose up -d --build

      - name: Deploy on Backend VM1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM1_BACK }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/app && docker-compose pull && docker-compose up -d --build

      - name: Deploy on Backend VM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM2_BACK }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/app && docker-compose pull && docker-compose up -d --build
